
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_CONST = 29;
  public static final int AND = 17;
  public static final int SAME = 14;
  public static final int IS = 2;
  public static final int ELSE = 5;
  public static final int PLUS = 20;
  public static final int RPAREN = 25;
  public static final int OR = 18;
  public static final int SAY = 7;
  public static final int HAS = 3;
  public static final int LOOP = 6;
  public static final int NOT = 13;
  public static final int FUNCTION = 11;
  public static final int AS = 15;
  public static final int LPAREN = 24;
  public static final int ID = 26;
  public static final int INT_CONST = 27;
  public static final int DO = 8;
  public static final int MAKE = 10;
  public static final int CAN = 19;
  public static final int MULT = 22;
  public static final int EOF = 0;
  public static final int WHEN = 4;
  public static final int DIV = 23;
  public static final int MINUS = 21;
  public static final int error = 1;
  public static final int FLOAT_CONST = 28;
  public static final int USE = 12;
  public static final int DONE = 9;
  public static final int BE = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IS",
  "HAS",
  "WHEN",
  "ELSE",
  "LOOP",
  "SAY",
  "DO",
  "DONE",
  "MAKE",
  "FUNCTION",
  "USE",
  "NOT",
  "SAME",
  "AS",
  "BE",
  "AND",
  "OR",
  "CAN",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LPAREN",
  "RPAREN",
  "ID",
  "INT_CONST",
  "FLOAT_CONST",
  "STRING_CONST"
  };
}

